[package]
name = "identify"
version = "0.1.0"
edition = "2021"

[dependencies]
petgraph = "0.7.1"
serde = "1.0.217"
serde_derive = "1.0.217"
serde_json = "1.0.138"
clap = { version = "4.5.29", features = ["derive"] }
