[package]
name = "identify"
version = "0.1.0"
edition = "2021"

[dependencies]
petgraph = "0.7.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
clap = { version = "4.0", features = ["derive"] }
