name: "Build and Push Nix Container"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Container version tag (e.g., v1.0.0)"
        required: true

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up caching for Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          extra_nix_config: |
            max-jobs = auto
            cores = 0

      - name: Configure GitHub token for Nix
        run: |
          mkdir -p ~/.config/nix
          echo "access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}" >> ~/.config/nix/nix.conf

      - name: Build and push intermediate derivations to Cachix
        run: cachix watch-exec airtool-dev -- nix build .#default
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Clean up old airtool-dev Docker images
        run: |
          docker image rm -f airtool-dev || true
          docker image rm -f ghcr.io/${{ github.repository_owner }}/airtool-dev:latest || true

      - name: Ensure result exists
        run: test -e result

      - name: Load Docker image
        run: |
          docker load < result
          docker tag airtool-dev ghcr.io/${{ github.repository_owner }}/airtool-dev:${{ github.event.inputs.version }}

      - name: Authenticate to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository_owner }}/airtool-dev:${{ github.event.inputs.version }}
